def call(JOB_NAME){
    snykscan()
    mavenHome = tool name: 'apache-maven-3.3.3'    
    def server = Artifactory.server '-1529600031@1456948926935'
    def buildInfo = Artifactory.newBuildInfo()    
    println "Performing build with maven at: ${mavenHome}"
    sh "${mavenHome}/bin/mvn -Djavax.net.ssl.trustStore=/opt/citools/etc/cacerts.keystore -Dmaven.test.skip=true clean package -U"
    buildInfo.env.collect()
    def uploadSpec = """{
        "files": [
         {
          "pattern": "dist/(*)",
          "target": "${JOB_NAME}/{1}"
         }
        ]
    }"""
    server.upload spec: uploadSpec, buildInfo: buildInfo
    if(BRANCH.contains("PR-")) {
                println "Branch: ${BRANCH} is a Pull Request, Docker build and publish will not be run."
    }else{
        println "Performing podman build && push"

        sh 'echo {\\"auths\\":{\\"https://artifactory.voya.net/v2/\\":{\\"auth\\":\\"$(echo -n "${REG_CRED_USR}:${REG_CRED_PSW}" | base64)\\"}}} > config.json'
                    sh '''
                    podman login -u ${REG_CRED_USR} -p ${REG_CRED_PSW} artifactory.voya.net/docker-virtual
                    podman build -t "artifactory.voya.net/docker-virtual/${APP_IMAGE}:${TAG}" --pull=true --file=Dockerfile .
                    podman push --log-level=debug "artifactory.voya.net/docker-virtual/${APP_IMAGE}:${TAG}" 
                    '''    
     }
}
